// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Allow Neon-first setups where only NEON_DATABASE_URL is configured.
    url: process.env["DATABASE_URL"] || process.env["NEON_DATABASE_URL"],
  },
});
