/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as ComisionesRouteImport } from './routes/comisiones'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CarteraModeloRouteImport } from './routes/cartera-modelo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioTokenRouteImport } from './routes/portfolio.$token'
import { Route as ClientesClientIdRouteImport } from './routes/clientes.$clientId'

const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const ComisionesRoute = ComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteraModeloRoute = CarteraModeloRouteImport.update({
  id: '/cartera-modelo',
  path: '/cartera-modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioTokenRoute = PortfolioTokenRouteImport.update({
  id: '/portfolio/$token',
  path: '/portfolio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClientIdRoute = ClientesClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartera-modelo': typeof CarteraModeloRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/comisiones': typeof ComisionesRoute
  '/precios': typeof PreciosRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/portfolio/$token': typeof PortfolioTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartera-modelo': typeof CarteraModeloRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/comisiones': typeof ComisionesRoute
  '/precios': typeof PreciosRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/portfolio/$token': typeof PortfolioTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartera-modelo': typeof CarteraModeloRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/comisiones': typeof ComisionesRoute
  '/precios': typeof PreciosRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/portfolio/$token': typeof PortfolioTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartera-modelo'
    | '/clientes'
    | '/comisiones'
    | '/precios'
    | '/clientes/$clientId'
    | '/portfolio/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartera-modelo'
    | '/clientes'
    | '/comisiones'
    | '/precios'
    | '/clientes/$clientId'
    | '/portfolio/$token'
  id:
    | '__root__'
    | '/'
    | '/cartera-modelo'
    | '/clientes'
    | '/comisiones'
    | '/precios'
    | '/clientes/$clientId'
    | '/portfolio/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteraModeloRoute: typeof CarteraModeloRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ComisionesRoute: typeof ComisionesRoute
  PreciosRoute: typeof PreciosRoute
  PortfolioTokenRoute: typeof PortfolioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comisiones': {
      id: '/comisiones'
      path: '/comisiones'
      fullPath: '/comisiones'
      preLoaderRoute: typeof ComisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartera-modelo': {
      id: '/cartera-modelo'
      path: '/cartera-modelo'
      fullPath: '/cartera-modelo'
      preLoaderRoute: typeof CarteraModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$token': {
      id: '/portfolio/$token'
      path: '/portfolio/$token'
      fullPath: '/portfolio/$token'
      preLoaderRoute: typeof PortfolioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clientId': {
      id: '/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof ClientesClientIdRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesClientIdRoute: typeof ClientesClientIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClientIdRoute: ClientesClientIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteraModeloRoute: CarteraModeloRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ComisionesRoute: ComisionesRoute,
  PreciosRoute: PreciosRoute,
  PortfolioTokenRoute: PortfolioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
